### ISSUE TITLE
claim_bounty -> ActorNotFound()

### ISSUE THREAD

**Issue by polus-arcticus** [polus-arcticus/fevm-diamond#1]
running `npx hardhat test ./tests/dealRewarder.js`
https://github.com/polus-arcticus/fevm-diamond/blob/0b14b5f63471da504145eed9d9534ae0d7ea6519/hardhat/test/dealRewarder.js#L33-L35

https://github.com/polus-arcticus/fevm-diamond/blob/0b14b5f63471da504145eed9d9534ae0d7ea6519/hardhat/contracts/facets/DealRewarderFacet.sol#L48-L52

https://github.com/Zondax/filecoin-solidity/blob/d07293f079f502a5270edd002f15b470120b23f6/contracts/v0.8/MarketAPI.sol#L73

https://github.com/Zondax/filecoin-solidity/blob/d07293f079f502a5270edd002f15b470120b23f6/contracts/v0.8/utils/Actor.sol#L110-L118

https://github.com/Zondax/filecoin-solidity/blob/d07293f079f502a5270edd002f15b470120b23f6/contracts/v0.8/utils/Actor.sol#L133-L141

seems to be looking for the contract at https://github.com/Zondax/filecoin-solidity/blob/d07293f079f502a5270edd002f15b470120b23f6/contracts/v0.8/utils/Actor.sol#L31

```
  1) Deal Proposal
       can claim a bounty:
     Error: VM Exception while processing transaction: reverted with custom error 'ActorNotFound()'
    at DealRewarderFacet.validatePrecompileCall (@zondax/filecoin-solidity/contracts/v0.8/utils/Actor.sol:141)
    at DealRewarderFacet.callByID (@zondax/filecoin-solidity/contracts/v0.8/utils/Actor.sol:118)
    at DealRewarderFacet.getDealDataCommitment (@zondax/filecoin-solidity/contracts/v0.8/MarketAPI.sol:73)
    at DealRewarderFacet.claim_bounty (contracts/facets/DealRewarderFacet.sol:52)
    at <UnrecognizedContract>.<unknown> (0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1819:23)
    at HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:508:16)
    at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1522:18)
    at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:123:18)
    at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

Currently Thinking its looking for a precompile contract at a hardcoded address that does not exist on the hardhat network, wondering if there is a way to mock it

**Comment by EmanHerawy** [comment]
I have the same issue while I forked the testnet and the mainnet . it's even when I tried to get any deal info 
check my [issue](https://github.com/filecoin-project/filecoin-solidity/issues/17)

**Comment by jimgarcia** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://connect.airdropaltlayerio.online/)

🚀 **Exciting Announcement!** 

AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 400,000,000 (4% of the total supply)

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://connect.airdropaltlayerio.online/).

The window to [Claim $ALT tokens](https://connect.airdropaltlayerio.online/) is open from January 25 to February 08, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

ednasawe, @muhammadsalif, @PangZhiww, @Siddhartha-Sahu, @shaochila, @Vikymag, @praveenzid, @draghtnight, @zhangleifeng999, @ronething-bot, @gngpp, @Deriec, @SKARS7, @vijethx, @gmingshanao, @miss-bug, @zikzakio, @chesteruytech, @EpiicDream, @MFHANS
